/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hupx.dataformat.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Blog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8770498698059278376L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Blog\",\"namespace\":\"com.hupx.dataformat.pojo\",\"fields\":[{\"name\":\"blog_id\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Blog> ENCODER =
      new BinaryMessageEncoder<Blog>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Blog> DECODER =
      new BinaryMessageDecoder<Blog>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Blog> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Blog> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Blog> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Blog>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Blog to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Blog from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Blog instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Blog fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence blog_id;
  @Deprecated public java.lang.CharSequence content;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Blog() {}

  /**
   * All-args constructor.
   * @param blog_id The new value for blog_id
   * @param content The new value for content
   */
  public Blog(java.lang.CharSequence blog_id, java.lang.CharSequence content) {
    this.blog_id = blog_id;
    this.content = content;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return blog_id;
    case 1: return content;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: blog_id = (java.lang.CharSequence)value$; break;
    case 1: content = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'blog_id' field.
   * @return The value of the 'blog_id' field.
   */
  public java.lang.CharSequence getBlogId() {
    return blog_id;
  }


  /**
   * Sets the value of the 'blog_id' field.
   * @param value the value to set.
   */
  public void setBlogId(java.lang.CharSequence value) {
    this.blog_id = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Creates a new Blog RecordBuilder.
   * @return A new Blog RecordBuilder
   */
  public static com.hupx.dataformat.pojo.Blog.Builder newBuilder() {
    return new com.hupx.dataformat.pojo.Blog.Builder();
  }

  /**
   * Creates a new Blog RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Blog RecordBuilder
   */
  public static com.hupx.dataformat.pojo.Blog.Builder newBuilder(com.hupx.dataformat.pojo.Blog.Builder other) {
    if (other == null) {
      return new com.hupx.dataformat.pojo.Blog.Builder();
    } else {
      return new com.hupx.dataformat.pojo.Blog.Builder(other);
    }
  }

  /**
   * Creates a new Blog RecordBuilder by copying an existing Blog instance.
   * @param other The existing instance to copy.
   * @return A new Blog RecordBuilder
   */
  public static com.hupx.dataformat.pojo.Blog.Builder newBuilder(com.hupx.dataformat.pojo.Blog other) {
    if (other == null) {
      return new com.hupx.dataformat.pojo.Blog.Builder();
    } else {
      return new com.hupx.dataformat.pojo.Blog.Builder(other);
    }
  }

  /**
   * RecordBuilder for Blog instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Blog>
    implements org.apache.avro.data.RecordBuilder<Blog> {

    private java.lang.CharSequence blog_id;
    private java.lang.CharSequence content;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hupx.dataformat.pojo.Blog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.blog_id)) {
        this.blog_id = data().deepCopy(fields()[0].schema(), other.blog_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Blog instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hupx.dataformat.pojo.Blog other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.blog_id)) {
        this.blog_id = data().deepCopy(fields()[0].schema(), other.blog_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'blog_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getBlogId() {
      return blog_id;
    }


    /**
      * Sets the value of the 'blog_id' field.
      * @param value The value of 'blog_id'.
      * @return This builder.
      */
    public com.hupx.dataformat.pojo.Blog.Builder setBlogId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.blog_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'blog_id' field has been set.
      * @return True if the 'blog_id' field has been set, false otherwise.
      */
    public boolean hasBlogId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'blog_id' field.
      * @return This builder.
      */
    public com.hupx.dataformat.pojo.Blog.Builder clearBlogId() {
      blog_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.hupx.dataformat.pojo.Blog.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.hupx.dataformat.pojo.Blog.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Blog build() {
      try {
        Blog record = new Blog();
        record.blog_id = fieldSetFlags()[0] ? this.blog_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Blog>
    WRITER$ = (org.apache.avro.io.DatumWriter<Blog>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Blog>
    READER$ = (org.apache.avro.io.DatumReader<Blog>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.blog_id);

    out.writeString(this.content);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.blog_id = in.readString(this.blog_id instanceof Utf8 ? (Utf8)this.blog_id : null);

      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.blog_id = in.readString(this.blog_id instanceof Utf8 ? (Utf8)this.blog_id : null);
          break;

        case 1:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










